[graph]
targets = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
    "RUSTSEC-2021-0145", # some Windows-only vuln by the `atty` crate brought in via `clap`.
    "RUSTSEC-2021-0139", # unmaintain ansi_term
    "RUSTSEC-2024-0375", # unmaintained atty
    "RUSTSEC-2024-0344", # curve25519-dalek 3.2.0 timing vuln, libp2p depends on it and is stuck on this version with the rust compiler mobilecoin uses
    "RUSTSEC-2024-0344", # curve25519-dalek 4.1.1 timing vuln, need to update bulletproofs-of to address this
    "RUSTSEC-2022-0093", # ed25519-dalek 1.0.1 serialization issue (libp2p dependency)
    "RUSTSEC-2020-0036", # failure 0.1.8 unmaintained
    "RUSTSEC-2019-0036", # failure 0.1.8 unsound issue
    "RUSTSEC-2024-0370", # proc-macro-error 1.0.4  unmaintained
    "RUSTSEC-2024-0336", # rustls potential infinite loop (libp2p dependency)
    "RUSTSEC-2024-0365", # diesel injection if input >4gb, need newer rust compiler to update
]

[licenses]
# TODO: Disabled since mobilecoin/ is too much of a mess right now
# unlicensed = "allow"
# allow = [
#     "Apache-2.0",
#     "Apache-2.0 WITH LLVM-exception",
#     "BSD-2-Clause",
#     "BSD-3-Clause",
#     "ISC",
#     "MIT",
#     "Unicode-DFS-2016",
#     "OpenSSL",
#     "GPL-3.0"
# ]
# deny = []
# copyleft = "deny"
# allow-osi-fsf-free = "neither"
# default = "deny"
# confidence-threshold = 0.8
# exceptions = []
# clarify = [
#     { name = "ring", expression = "MIT AND ISC AND OpenSSL", license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }] },
# ]

clarify = [
    { name = "ring", expression = "MIT AND ISC AND OpenSSL", license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }] },
]


[bans]
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow" # Could be denied once 'allow-wildcard-paths' is released (https://github.com/EmbarkStudios/cargo-deny/pull/487)
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
